[versions]
agp = "8.13.2"
annotation = "1.9.1"
coilCompose = "3.3.0"
converterMoshi = "3.0.0"
datastore = "1.2.0"
decompose = "3.4.0"
desugar_jdk_libs = "2.1.5"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
jetbrainsKotlinJvm = "2.3.0"
appcompat = "1.7.1"
material = "1.13.0"
moshi = "1.15.2"
moshiKotlin = "1.15.2"
okhttpBom = "5.3.2"
protobufKotlinLite = "4.32.1"
retrofit = "3.0.0"
loggingInterceptor = "5.3.2"
gradle = "8.13.2"
koin-bom = "4.1.1"
koin-annotations = "2.3.1"
kotlinxCoroutinesVersion = "1.10.2"
playServicesLocation = "21.3.0"
detekt = "1.23.8"
material3 = "1.4.0"
materialIconsExtended = "1.7.8"
protobufPlugin = "0.9.6"
datastoreCore = "1.2.0"
buildConfig = "6.0.7"
ksp = "2.3.2"

javaVersion = "17"
compileSdk = "36"
minSdk = "23"
timber = "5.0.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
decompose-extensions-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-bom" }
koin-compose-viewwmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-bom" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobufKotlinLite" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }
build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesVersion" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastoreCore" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
android-library = { id = "com.android.library", version.ref = "agp" }
detekt-plugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
protobuf-plugin = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
gmazzo-buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

conventions-koin = { id = "ru.agrachev.convention.plugins.koin", version = "unspecified" }
conventions-test = { id = "ru.agrachev.convention.plugins.test", version = "unspecified" }
conventions-repo-remote = { id = "ru.agrachev.convention.plugins.remoteRepo", version = "unspecified" }
conventions-compose = { id = "ru.agrachev.convention.plugins.compose", version = "unspecified" }
conventions-feature-definition = { id = "ru.agrachev.convention.plugins.featureDefinition", version = "unspecified" }
conventions-android-library = { id = "ru.agrachev.convention.plugins.androidLibrary", version = "unspecified" }
conventions-android-application = { id = "ru.agrachev.convention.plugins.androidApplication", version = "unspecified" }
conventions-kotlin-library = { id = "ru.agrachev.convention.plugins.kotlinLibrary", version = "unspecified" }
